title: "Casper Directory"
remote_theme: pmarsceill/just-the-docs
search_enabled: true
theme: jekyll-theme-cayman

# Aux links for the upper right navigation
aux_links:
  "Casper.Directory on GitHub":
    - "//github.com/make-software/casper.directory"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/make-software/casper.directory" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
